//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.orderDetailes = new HashSet<orderDetaile>();
        }
    
        public int id { get; set; }
        public string productName { get; set; }
        public string productImage { get; set; }
        public string description { get; set; }
        public Nullable<double> price { get; set; }
        public string code { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> numberOfProduct { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderDetaile> orderDetailes { get; set; }
    }
}
